version: '3.8'
services:
  app:
    build: .
    container_name: fall-festival-server-prod
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env