services:
  app:
    image: festival-app:latest
    container_name: festival-server-prod
    ports:
      - "80:8080"
    env_file:
      - .env.prod
    volumes:
      - /home/festival/logs:/app/logs
    networks:
      - festival-network
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 45s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  festival-network:
    driver: bridge
