services:
  nginx:
    image: nginx:latest
    container_name: festival-nginx-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d
      - /home/festival/data/certbot/www:/var/www/certbot
      - /home/festival/data/certbot/conf:/etc/letsencrypt
    networks:
      - festival-network
    restart: unless-stopped

networks:
  festival-network:
    driver: bridge
