server:
  port: 8080

spring:
  application:
    name: festival
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create   #초기 개발에는 create로 하시죠
    show-sql: true       #쿼리출력하려고
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    org.springframework: INFO

---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://localhost:3307/festival
    username: root
    password:

---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${PROD_DB_URL}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    org.springframework: INFO
