name: Fall Festival Spring Boot Server Auto Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. JDK 17 설정
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # 3. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # 4. 애플리케이션 빌드
      - name: Build with Gradle
        run: ./gradlew build -x test

      # 5. Docker 이미지 빌드 및 저장
      - name: Build Docker image
        run: |
          docker build -t festival-app .
          docker save festival-app > festival-app.tar

      # 6. 서버로 파일 전송
      - name: Transfer files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: |
            festival-app.tar
            docker-compose-prod.yml
            scripts/deploy.sh
            scripts/health-check.sh
          target: /home/festival/

      # 7. 서버에서 무중단 배포 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            cd /home/festival
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh

      # 8. 배포 완료 알림
      - name: Notify deployment success
        if: success()
        run: |
          echo "Fall Festival 서버 배포가 성공적으로 완료되었습니다!"
          echo "배포 시간: $(date)"
